config/routes.rb
Runblr::Application.routes.draw do
  resources :users, only: [:create, :new, :destroy, :show, :update, :edit] do
    get 'dashboard'
    resources :follows, only: [:create, :destroy]
  end

  resource :session, :only => [:create, :destroy, :new]

  resource :password_reset

  resources :posts do
    member do
      post "like"
      post "unlike"
    end
    resources :comments, only: [:create, :new, :show, :destroy, :edit] do
      member do
        post "like"
        post "unlike"
      end
    end
  end

  root to: 'sessions#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :parent_comment_id, :post_id, :user_id

  validates :body, presence: true
  validates :user, presence: true
  validates :post, presence: true

  belongs_to :post, inverse_of: :comments
  belongs_to :user, inverse_of: :comments
  has_many :user_comment_likes, inverse_of: :comment

  has_many( :child_comments,
           class_name: "Comment",
           foreign_key: :parent_comment_id,
           primary_key: :id)
  belongs_to :parent_comment, class_name: "Comment", foreign_key: :parent_comment_id, primary_key: :id

  def likes
    self.user_comment_likes.sum(:value)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :like, :unlike]
  before_filter :comment_exists?, only: [:edit, :show, :update, :like, :unlike]
  before_filter :user_owns_comment?, only: [:edit, :update]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html { render partial: "new_comment_template", locals: { post: @post, comment: @comment } }
      end
    # else
    #   flash[:errors] = @comment.errors.full_messages
    #   head :ok
    end
  end

  def new
    @comment = Comment.new
  end

  def edit
    @post = params[:comment]
  end

  def show
    @post = params[:comment]
    redirect_to :back
  end

  def update
    if @comment.update_attributes(params[:comment])
      redirect_to :back
    else
      flash.now[:errors] = @comment.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    @comment.delete
    
    head :ok
  end

  def like
    @comment = Comment.find_by_id(params[:id])
    like_total(1)

    respond_to do |format|
      format.html { render partial: "comment_likes_information", comment: @comment}
    end
  end

  def unlike
    @comment = Comment.find_by_id(params[:id])
    like_total(0)

    respond_to do |format|
      format.html { render partial: "comment_likes_information", comment: @comment}
    end
  end

  private
    def comment_exists?
      @comment = Comment.includes(:user_comment_likes).find_by_id(params[:id])
      redirect_to :back unless @comment
    end

    def like_total(direction)
      @user_comment_like = UserCommentLike.find_by_comment_id_and_user_id(@comment.id, current_user.id)

      if @user_comment_like
        @user_comment_like.update_attributes(value: direction)
      else
        @comment.user_comment_likes.create(user_id: current_user.id, value: direction)
      end

      # redirect_to :back
    end

    def user_owns_comment?
      redirect_to :back unless @comment.user == current_user
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_partial(comment, comments_by_parent)
    render(
      :partial => "comments/comment",
      :locals => {
        :comment => comment,
        :comments_by_parent => comments_by_parent
      }
    )
  end
end

app/views/comments/_comment.html.erb
<div class="sub-comment">
  <div class="comment-container group">
    <div class="comment-left">
      <div class="username-link-footer-container">
        <div class="username-link-container">  <%= link_to comment.user.username, user_url(comment.user), :class => "username-link" %>
          <% unless current_user == comment.user %>
              <li><%= render "users/follow_button", follower: comment.user %></li>
          <% end %>
        </div>
      </div>

    
      <div>
        <a class="post_avatar_link" href="<%= user_url(comment.user) %>">
          <div>
            <% if comment.user.has_profile_picture %>
              <img src="<%= comment.user.profile_picture.url(:small) %>">
            <% else %>
              <img src="<%=asset_path "blank_profile.png"%>">
            <% end %>
          </div>
        </a>
      </div>
    </div>
    <li class="comment-body">  <%= comment.body %> </li>
  </div>
  <ul>
    
    <div class="comment-footer group">
      <div class="comment-likes-container">
        <%= render "comments/likes_template", comment: comment %>
      </div>
      
      <% if comment.user == current_user %>
      
        <div class="delete-comment-container">
    
          <form action="<%= post_comment_url(comment.post.id, comment.id) %>" method="put"
                 class="delete-comment" data-id="<%= comment.id %>">
            <input type="hidden" name="authenticity_token"
                                value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">

            <input type="submit" name="commit" value="Delete" class="delete-post-button" data-confirm='Are you sure?'>
          </form>
    
        </div>
      <% end %>
    </div>
    
    <div class="post-comment-title"> Reply to this comment.
      <div class="new-comment-container hide">
        <form action="<%= post_comments_url(comment.post.id) %>" method="POST" class="new-comment-form" post-id="<%= comment.post.id %>">
          <textarea name="comment[body]" placeholder="Enter comment here." class="comment-text-box"></textarea><br>
            <input type="submit" class="comment-button-submit">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="comment[parent_comment_id]" value="<%= comment.id %>">
        </form>
      </div>
    </div>
    
    

  </ul>

  <ul>
    <% comments_by_parent[comment.id].each do |child_comment| %>
      <%= comment_partial(child_comment, comments_by_parent) %>
    <% end %>
  </ul>
</div>

app/views/comments/_comment_likes_information.html.erb
<div><%= @comment.likes %> <%=  @comment.likes == 1 ? "like" : "likes" %> </div>
<ul>
    <% @comment.user_comment_likes.each do |user_comment_like| %>
      <% if user_comment_like.value == 1 %>
          <% user = User.find_by_id(user_comment_like.user_id) %>
          <div class="username-link-container">
            <li><%= link_to user.username, user_url(user), :class => "username-link" %> likes this </li>
            <% next if current_user == user %>
            <!-- <% if current_user.followed_users.include?(user) %>
              <td><%= button_to "Unfollow", user_follow_url(user.id, current_user.id), method: :delete %></td>
            <% else %>
              <td><%= button_to "Follow", user_follows_url(user.id) %></td>
            <% end %> -->
            <li> <%= render "users/follow_button", follower: user %> </li>
          </div>
          <br>
      <% end %>
    <% end %>
</ul>

app/views/comments/_comments_template.html.erb
<% comments_by_parent = post.comments_by_parent %>
<% comments_by_parent[nil].each do |top_level_comments| %>
    <%= comment_partial(top_level_comments, comments_by_parent) %>
<% end %>

app/views/comments/_likes_template.html.erb
<!-- <% unless current_user.likes_comment?(comment) %>
  <li><%= link_to "like",  like_post_comment_url(comment.post, comment), method: :post%></li>
<% else %>
  <li><%= link_to "unlike",  unlike_post_comment_url(comment.post, comment), method: :post%></li>
<% end %> -->

<li>

<div class="comment-like-button-container">
  <span class="comment-like-buttons<%= " comment-can-like" if !current_user.likes_comment?(comment) %> ">

    <form action="<%= unlike_post_comment_url(comment.post, comment) %> " method="post"
           class="comment-unlike comments-liking-form" data-id="<%= comment.id %>">
      <input type="hidden" name="authenticity_token"
                          value="<%= form_authenticity_token %>">

      <input type="submit" name="commit" value="Unlike" class="like-button-submit">
    </form>

    <form action="<%= like_post_comment_url(comment.post, comment) %>" method="post"
           class="comment-like comments-liking-form" data-id="<%= comment.id %>">
      <input type="hidden" name="authenticity_token"
                          value="<%= form_authenticity_token %>">

      <input type="submit" name="commit" value="Like" class="like-button-submit">
    </form>

  </span>
</div>

</li>

<li class="comment-like-info-container data-comment-likes-<%= comment.id %>">
  <div><%= comment.likes %> <%=  comment.likes == 1 ? "like" : "likes" %></div>
  <ul>

      <% comment.user_comment_likes.each do |user_comment_like| %>
        <% if user_comment_like.value == 1 %>
            <% user = User.find_by_id(user_comment_like.user_id) %>
              <div class="username-link-container">
                <li><%= link_to user.username, user_url(user), :class => "username-link" %> likes this </li>
                <% next if current_user == user %>
                <!-- <% if current_user.followed_users.include?(user) %>
                  <td><%= button_to "Unfollow", user_follow_url(user.id, current_user.id), method: :delete %></td>
                <% else %>
                  <td><%= button_to "Follow", user_follows_url(user.id) %></td>
                <% end %> -->
                <li><%= render "users/follow_button", follower: user %></li>
              </div>
              <br>
        <% end %>
      <% end %>

  </ul>
</li>

app/views/comments/_new_comment_template.html.erb
<% comments_by_parent = post.comments_by_parent %>
<% comments_by_parent[nil].each do |top_level_comments| %>
    <%= comment_partial(top_level_comments, comments_by_parent) %>
<% end %>

app/views/comments/_new_template.html.erb
<div class="new-comment-container hide">
  <form action="<%= post_comments_url(post.id) %>" method="POST" class="new-comment-form" post-id="<%= post.id %>">
    <textarea name="comment[body]" placeholder="Enter comment here." class="comment-text-box"></textarea><br>
    <input type="submit" class="comment-button-submit">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  </form>
</div>