config/routes.rb
Runblr::Application.routes.draw do
  resources :users, only: [:create, :new, :destroy, :show, :update, :edit] do
    get 'dashboard'
    resources :follows, only: [:create, :destroy]
  end

  resource :session, :only => [:create, :destroy, :new]

  resource :password_reset

  resources :posts do
    member do
      post "like"
      post "unlike"
    end
    resources :comments, only: [:create, :new, :show, :destroy, :edit] do
      member do
        post "like"
        post "unlike"
      end
    end
  end

  root to: 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :session_token, :email, :profile_picture, :has_profile_picture
  after_initialize :ensure_session_token
  attr_reader :password

  validates :username, :session_token, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :username, :length => 6..20
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }

  has_attached_file :profile_picture, :styles => {
          :big => "600x600>",
          :small => "75x75#"
        }

  has_many(
    :inbound_follows,
    :class_name => "Follow",
    :foreign_key => :runner_followee_id,
    :primary_key => :id
  )

  has_many(
    :followers,
    :class_name => "User",
    :through => :inbound_follows,
    :source => :follower
  )

  has_many(
    :outbound_follows,
    :class_name => "Follow",
    :foreign_key => :runner_follower_id,
    :primary_key => :id
  )

  has_many(
    :followed_users,
    :class_name => "User",
    :through => :outbound_follows,
    :source => :followee
  )

  has_many :posts, inverse_of: :user
  has_many :user_post_likes, inverse_of: :user
  has_many :comments, inverse_of: :user
  has_many :user_comment_likes, inverse_of: :user


  def password=(pw_string)
    @password = pw_string
    self.password_digest = BCrypt::Password.create(pw_string)
  end

  def reset_session_token!
    self.update_attributes(session_token: SecureRandom.urlsafe_base64)
  end

  def is_password?(pass)
    BCrypt::Password.new(self.password_digest).is_password?(pass)
  end

  def likes_post?(post)
    @user_post_like = UserPostLike.find_by_post_id_and_user_id(post.id, self.id)
    return false if @user_post_like.nil?
    @user_post_like.value == 1 ? true : false
  end

  def likes_comment?(comment)
    @user_comment_like = UserCommentLike.find_by_comment_id_and_user_id(comment.id, self.id)
    return false if @user_comment_like.nil?
    @user_comment_like.value == 1 ? true : false
  end

  def get_user_posts_feed
    all_posts = []
    all_posts.concat(self.posts)
    self.followed_users.each do |followed_user|
      all_posts = all_posts.concat(followed_user.posts)
    end
    return all_posts.sort_by {|x| x.created_at }
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver!
  end

  def send_password_reset
    self.password_reset_token = SecureRandom.urlsafe_base64(16)
    self.save!
    UserMailer.password_reset(self).deliver!
  end

  private

     def ensure_session_token
       self.session_token ||= SecureRandom.urlsafe_base64
     end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:dashboard, :settings, :edit]
  before_filter :new_user?, only: [:new, :create]

  def dashboard
    @user = User.find_by_id(params[:user_id])
    @post = Post.new
  end

  def settings
    @user = User.find_by_id(params[:user_id])
  end

  def create
    @user = User.new(params[:user])
    @user.has_profile_picture = false
    if @user.save
      login_user!(@user)

      # @user.send_welcome_email

      redirect_to user_dashboard_url(current_user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end

  def new
    @user = User.new
    render :new
  end



  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Settings updated"
      redirect_to :back
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to :back
    end

  end

  def show
    @user = User.find_by_id(params[:id])

    if @user
      render :show
    else
      redirect_to user_dashboard_url(current_user)
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to new_session_url
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<div class="follow-button-container">
  <span class="follow-buttons<%= " can-follow" if !current_user.followed_users.include?(follower) %> user_follow_<%= follower.id %>">
  <!-- <td><%= button_to "Unfollow", user_follow_url(follower.id, current_user.id), method: :delete, form_class: "unfollow" %></td>
  <td><%= button_to "Follow", user_follows_url(follower.id), form_class: "follow" %></td> -->

  <form action="<%= user_follow_url(follower.id, current_user.id) %>" method="post"
         class="unfollow follow-form" data-id="<%= follower.id %>">
    <input type="hidden" name="authenticity_token"
                        value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">

    <input type="submit" name="commit" value="Unfollow" class="follow-button-submit">
  </form>

  <form action="<%= user_follows_url(follower.id) %>" method="post"
         class="follow follow-form" data-id="<%= follower.id %>">
    <input type="hidden" name="authenticity_token"
                        value="<%= form_authenticity_token %>">


    <input type="submit" name="commit" value="Follow" class="follow-button-submit">
  </form>

  </span>

</div>

app/views/users/_form.html.erb
<form action="<%= provided_url %>" method="post">
  <label for="user_username">Username</label>
  <input
    type="text"
    name="user[username]"
    value="<%= user.username %>"
    id="user_username">

  <label for="user_password">Password</label>
  <input
    type="password"
    name="user[password]"
    id="user_password">

  <input type="submit">
</form>

app/views/users/_header_partial.html.erb
<div id="header_container">

  <div id="header">
    <h1 class="dashboard-logo">
      <a class="logo_anchor" href="<%= user_dashboard_url(current_user) %>">runblr.</a>
    </h1>
    <div id="tabs_outter_container">
      <div id="user_tools">
        <div class="tab tab_home">
          <%= link_to "HO", user_dashboard_url(current_user) %>
        </div>
        <div class="tab tab_settings">
          <%= link_to "SE", edit_user_url(current_user) %>
        </div>
        <div class="tab tab_log_out">
          <%= link_to "LO", session_url, :method => :delete %>
        </div>
        <div class="tab tab_search">
          SEARCH
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_right_column_template.html.erb
<h1 id="blog-holder">
  <%= link_to "Profile Page", user_url(current_user), id: "blog_link" %>
</h1>
<ul class="blog_menu">

  <li class="control_item group">
    <div class="right_link">
      Followers
    </div>
    <div class="right_link_amount">
      <%= current_user.followers.count %>
    </div>
  </li>
  <li class="control_item group">
    <% current_user.followers.sort.each do |follower| %>
      <%= link_to follower.username, user_url(follower) %> <br>
        <%= render "users/follow_button", follower: follower %>
      <!-- <% if current_user.followed_users.include?(follower) %>
        <td><%= button_to "Unfollow", user_follow_url(follower.id, current_user.id), method: :delete %></td>
      <% else %>
        <td><%= button_to "Follow", user_follows_url(follower.id) %></td>
      <% end %> -->


    <!-- <% if current_user.followed_users.include?(follower) %>
      <td><%= button_to "Unfollow", user_follow_url(follower.id, current_user.id), method: :delete %></td>
    <% else %>
      <td><%= button_to "Follow", user_follows_url(follower.id) %></td>
    <% end %> -->

  <% end %>

  </li>
  <li class="control_item group">
    <div class="right_link">
      Following
    </div>
    <div class="right_link_amount">
      <%= current_user.followed_users.count %>
    </div>
  <li class="control_item group">
    <% current_user.followed_users.sort.each do |followed_user| %>
      <%= link_to followed_user.username, user_url(followed_user) %> <br>

        <!-- <td><%= button_to "Unfollow", user_follow_url(followed_user.id, current_user.id), method: :delete %></td> -->
          <%= render "users/follow_button", follower: followed_user %>
    <% end %>

  </li>

</ul>

app/views/users/_user_form.html.erb
<form action="<%= provided_url %>" method="post">
  <label for="user_username">Username</label>
  <input
    type="text"
    name="user[username]"
    value="<%= user.username %>"
    id="user_username">

  <label for="user_email">Email</label>
  <input
    type="text"
    name="user[email]"
    value="<%= user.email %>"
    id="user_email">

  <label for="user_password">Password</label>
  <input
    type="password"
    name="user[password]"
    id="user_password">

  <input type="submit">
</form>

app/views/users/dashboard.html.erb
<head>
  <title>Runblr </title>
  <%= stylesheet_link_tag    "dashboard" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="dashboard_index">
  <div class="container group">

    <%= render "users/header_partial"%>

    <div id="content" class="group">

      <div id="right_column">
        <h1 id="blog-holder">
          <%= link_to "Profile Page", user_url(current_user), id: "blog_link" %>
        </h1>
        <ul class="blog_menu">

          <li class="control_item group">
            <div class="right_link">
              Followers
            </div>
            <div class="right_link_amount">
              <%= current_user.followers.count %>
            </div>
          </li>
          <li class="control_item group">
            <% current_user.followers.sort.each do |follower| %>
              <%= link_to follower.username, user_url(follower) %> <br>
                <%= render "users/follow_button", follower: follower %>
              <!-- <% if current_user.followed_users.include?(follower) %>
                <td><%= button_to "Unfollow", user_follow_url(follower.id, current_user.id), method: :delete %></td>
              <% else %>
                <td><%= button_to "Follow", user_follows_url(follower.id) %></td>
              <% end %> -->


            <!-- <% if current_user.followed_users.include?(follower) %>
              <td><%= button_to "Unfollow", user_follow_url(follower.id, current_user.id), method: :delete %></td>
            <% else %>
              <td><%= button_to "Follow", user_follows_url(follower.id) %></td>
            <% end %> -->

          <% end %>

          </li>
          <li class="control_item group">
            <div class="right_link">
              Following
            </div>
            <div class="right_link_amount">
              <%= current_user.followed_users.count %>
            </div>
          <li class="control_item group">
            <% current_user.followed_users.sort.each do |followed_user| %>
              <%= link_to followed_user.username, user_url(followed_user) %> <br>

                <!-- <td><%= button_to "Unfollow", user_follow_url(followed_user.id, current_user.id), method: :delete %></td> -->
                  <%= render "users/follow_button", follower: followed_user %>
            <% end %>

          </li>

        </ul>
      </div>

      <div id="left_column">

        <ol id="posts">
          <li class="post_container new_post_buttons_container">
            <div class="new_post_buttons">
              <nav id="post_buttons">
                <a href="#" class="new_post_label run-click">
                  RU
                </a>
                <a href="#" class="new_post_label photo-click">
                  PH
                </a>
                <a href="#" class="new_post_label link-click">
                  LI
                </a>
                <a href="#" class="new_post_label quote-click">
                  QU
                </a>
                <a href="#" class="new_post_label video-click">
                  VI
                </a>
              </nav>

              <!-- POST FORMS -->


              <div class="new_post_form_container">

                <div class="new_post_form run-post hide">
                  <%= render "posts/post_form", post: @post, post_type: "run" %>
                </div>

                <div class="new_post_form photo-post hide">
                  <%= render "posts/post_form", post: @post, post_type: "photo" %>
                </div>

                <div class="new_post_form link-post hide">
                  <%= render "posts/post_form", post: @post, post_type: "link" %>
                </div>

                <div class="new_post_form quote-post hide">
                  <%= render "posts/post_form", post: @post, post_type: "quote" %>
                </div>

                <div class="new_post_form video-post hide">
                  <%= render "posts/post_form", post: @post, post_type: "video" %>
                </div>

              </div>



            </div>
            <div class="post_avatar">
              <a class="post_avatar_link" href="<%= user_url(current_user) %>">
                <% if current_user.has_profile_picture %>
                  <img src="<%= current_user.profile_picture.url(:small) %>">
                <% else %>
                  <img src="<%=asset_path "blank_profile.png"%>">
                <% end %>
              </a>
            </div>
          </li>

          <!-- START POSTS -->

          <%= render "posts/show_template", user: current_user, show_all: true %>

        </ol>
      </div>
    </div>
  </div>

</body>

<script>
$(document).ready(function(event){
  

  // FOLLOW BUTTONS

  function toggleFollowButtons ($dataid) {
      $(".user_follow_"+$dataid).toggleClass("can-follow");
  }
  
  $(".dashboard_index").on("submit", ".follow-form", function (event) {
    event.preventDefault();
    var $currentTarget = $(event.currentTarget);

    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: $currentTarget.serializeJSON(),
      success: function (right_column) {
        toggleFollowButtons($form.attr("data-id"));
        $("#right_column").html(right_column);

      }
    });
  });

  // NEW POST
  

  // $("form.post-form").on("submit", function (event) {
  //   event.preventDefault();
  // 
  //   var $currentTarget = $(event.currentTarget);
  //   var data = $currentTarget.serializeJSON();
  //   var $form = $(this);
  // 
  //   $.ajax({
  //     url: $form.attr("action"),
  //     type: "POST",
  //     data: data,
  //     success: function (post) {
  //       $("div.posts-list").prepend(post);
  //       $("."+data.post.post_type+"-post").toggleClass("hide");
  //       $form.each(function() {
  //         this.reset();
  //       });
  //     }
  //   });
  // });
  // 
  // function handle_files(files) {
  //   var file = files[0];
  //   var reader = new FileReader();
  //   reader.onload = function(e) {
  //     // you need to send e.target.result in your $.ajax request
  //     console.log(this.result);
  //   }
  //   reader.readAsDataURL(file);
  // }
  
  // DELETE POST
  
  $(".posts-container").on("submit", ".delete-post", function (event) {
    event.preventDefault();

    var $currentTarget = $(event.currentTarget);
    var $post = $(this).parents(".post_container");
    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "DELETE",
      success: function () {
        $post.remove();
      }
    });
  });

  // POST LIKES

  function togglePostLikeButtons ($button) {
    $button
      .parents(".like-buttons")
      .toggleClass("can-like");
  }

  $(".posts-container").on("submit", ".posts-liking-form", function (event) {
    event.preventDefault();
    var $currentTarget = $(event.currentTarget);

    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: $currentTarget.serializeJSON(),
      success: function (like_info) {
        togglePostLikeButtons($currentTarget);
        $(".data-post-likes-"+$form.attr("data-id")).html(like_info)
      }
    });
  });

  // NEW COMMENT

  $(".posts-container").on("submit", ".new-comment-form", function (event) {
    event.preventDefault();

    var $currentTarget = $(event.currentTarget);
    var data = $currentTarget.serializeJSON();
    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: data,
      success: function (comments) {
        $(".data-post-comments-"+$form.attr("post-id")).html(comments)
        $form.each(function() {
          this.reset();
        });
      }
    });
  });

  // DELETE COMMENT
  
  $(".posts-container").on("submit", ".delete-comment", function (event) {
    event.preventDefault();

    var $currentTarget = $(event.currentTarget);
    var $comment = $(this).parents(".sub-comment:first");
    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "DELETE",
      success: function () {
        $comment.remove();
      }
    });
  });

  // COMMENT LIKES

  function toggleCommentLikeButtons ($button) {
    $button
      .parents(".comment-like-buttons")
      .toggleClass("comment-can-like");
  }

  $(".posts-container").on("submit", ".comments-liking-form", function (event) {
    event.preventDefault();
    var $currentTarget = $(event.currentTarget);

    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: $currentTarget.serializeJSON(),
      success: function (like_info) {
        toggleCommentLikeButtons($currentTarget);
        $(".data-comment-likes-"+$form.attr("data-id")).html(like_info)
      }
    });
  });

  // NEW POST BUTTONS

  $(".run-click").on("click", function() {
    $(".run-post").toggleClass("hide");
    $(".photo-post").addClass("hide");
    $(".link-post").addClass("hide");
    $(".quote-post").addClass("hide");
    $(".video-post").addClass("hide");
  });

  $(".photo-click").on("click", function() {
    $(".photo-post").toggleClass("hide");
    $(".run-post").addClass("hide");
    $(".link-post").addClass("hide");
    $(".quote-post").addClass("hide");
    $(".video-post").addClass("hide");
  });

  $(".link-click").on("click", function() {
    $(".link-post").toggleClass("hide");
    $(".photo-post").addClass("hide");
    $(".run-post").addClass("hide");
    $(".quote-post").addClass("hide");
    $(".video-post").addClass("hide");
  });

  $(".quote-click").on("click", function() {
    $(".quote-post").toggleClass("hide");
    $(".photo-post").addClass("hide");
    $(".link-post").addClass("hide");
    $(".run-post").addClass("hide");
    $(".video-post").addClass("hide");
  });

  $(".video-click").on("click", function() {
    $(".video-post").toggleClass("hide");
    $(".photo-post").addClass("hide");
    $(".link-post").addClass("hide");
    $(".quote-post").addClass("hide");
    $(".run-post").addClass("hide");
  });

  // HOVER FOLLOW BUTTONS

  $(document).on('mouseover', ".username-link-container", function() {
    $(this).find(".follow-button-container").show();
  }).on('mouseout',  ".username-link-container", function() {
    $(this).find(".follow-button-container").hide();
  });

  // POP UP COMMENT BOXES
  
  $(document).on("click", ".post-comment-title", function() {
    $(this).find(".new-comment-container").toggleClass("hide");
  }).on("click", ".post-comment-title", function() {
    $(this).find(".comment-text-box").click(function(e) {
    return false;
  });
  });
});

// AUTOFILL POSTS

$('.fill-form-run').on("click", function(event) {
  event.preventDefault();
  
  $('.post_run_title').val("Ran Over Williamsburg Bridge");
  $('.post_date').val("2014-01-12");
  $('.post_time').val("13:02:00");
  $('.post_workout_type').val("Tempo");
  $('.post_miles').val("9.5");
  $('.post_hours').val("1");
  $('.post_minutes').val("10");
  $('.post_seconds').val("03");
  $('.post_run_description').val("Happy new year! I had a nice tempo run over the bridge. My legs weren't too sore.")
  
});

$('.fill-form-link').on("click", function(event) {
  event.preventDefault();
  
  $('.post_link_title').val("Congratulations Mary!!");
  $('.post_link_url').val("http://www.iaaf.org/news/report/mary-cain-1000m-world-record");
});

$('.fill-form-quote').on("click", function(event) {
  event.preventDefault();
  
  $('.post_quote_title').val("Pre");
  $('.post_quote_description').val("To give anything less than your best, is to sacrifice the gift. -Steve Prefontaine");
});

$('.fill-form-video').on("click", function(event) {
  event.preventDefault();
  
  $('.post_video_title').val("Gatlin vs. Bolt");
  $('.post_video_url').val("http://www.youtube.com/watch?v=MAz6yRznoiM");
});

</script>

app/views/users/edit.html.erb
<head>
  <title>Runblr </title>

  <%= stylesheet_link_tag    "dashboard" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="dashboard_index">
  <div class="container shift-edit">
    <%= render "users/header_partial"%>

    <div class="edit-title">
      <h2> Edit Information: </h2>
    </div>
    <form class="edit-user-info-form" action="<%= user_url(current_user) %>" method="post">
      <input type="hidden" name="_method" value="PUT">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

      <div class="signup_forms_panel group">
        <div class="form-row">
          <label for="user_email">
            <input
              type="text"
              name="user[email]"
              value="<%= @user.email %>"
              id="user_email"
              placeholder='Email'
              class="entry">
          </label>
        </div>
        <div class="form-row">
          <label for="user_password">
            <input
              type="password"
              name="user[password]"
              id="user_password"
              placeholder='Password'
              class="entry">
          </label>
        </div>
        <div class="form-row">
          <label for="user_username">
            <input
              type="text"
              name="user[username]"
              value="<%= @user.username %>"
              id="user_username"
              placeholder='Username'
              class="entry">
          </label>
        </div>
      </div><br>
      <% if flash[:notice] %>
        <%= flash[:notice] %> <br><br>
      <% end %>
      <% if flash[:errors] %>
          <%= render "layouts/errors" %>
      <% end %>
      <div class="edit_forms_button group submit-post">
        <input class="edit-button" type="submit" value="Update">
      </div>
    </form>

    <div class="edit-title">
      <h2> Upload Profile Picture: </h2>
    </div>
    
    <div class="show_avatar_on_edit">
        <% if current_user.has_profile_picture %>
          <img src="<%= current_user.profile_picture.url(:small) %>">
        <% else %>
          <img src="<%=asset_path "blank_profile.png"%>">
        <% end %>
    </div>
    
    <form action="<%= user_url(current_user) %>" method="POST"  enctype="multipart/form-data" class="edit-user-info-form">
      <input type="hidden" name="_method" value="PUT">
      <input type="hidden" name="user[has_profile_picture]" value="true">
      <div class="upload-profile-picture">
        <input type="file" name="user[profile_picture]">
      </div>
      <div class="submit-post submit-profile-picture">
        <input type="Submit" value="Submit">
      </div>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </form>
    

    
  </div>

</body>

app/views/users/new.html.erb
<head>
  <title>Sign Up | Runblr </title>
  <%= stylesheet_link_tag    "sign_in" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body id="account_logged_out_dashboard">

  <div class="fullscreen_post_bg">
    <!-- <img class="fullscreen_post_image" src="http://anime-wallpapers.com/images/800x600/naruto-running.jpg"> -->
    <img class="fullscreen_post_image" src="<%=asset_path "core.jpg"%>">
  </div>
  <div class="fullscreen_post_footer">
    <div class="fullscreen_post_posted_by show">
    </div>
  </div>

  <div class="dash_b_form_container">
    <div class="dash_b_form_header">
      <h1 class="logo">
        runblr.
      </h1>
      <h2 class="subheading">
        Follow the runners you've been hearing about.
        <br>
        Share the running that you love.
      </h2>
    </div>
    <div class="dash_b_form">
      <form action="<%= users_url %>" method="post">
        <div class="signup_forms_panel group">
          <div class="form-row">
            <label for="user_email">
              <input
                type="text"
                name="user[email]"
                value="<%= @user.email %>"
                id="user_email"
                placeholder='Email'
                class="entry">
            </label>
          </div>
          <div class="form-row">
            <label for="user_password">
              <input
                type="password"
                name="user[password]"
                id="user_password"
                placeholder='Password'
                class="entry">
            </label>
          </div>
          <div class="form-row">
            <label for="user_username">
              <input
                type="text"
                name="user[username]"
                value="<%= @user.username %>"
                id="user_username"
                placeholder='Username'
                class="entry">
            </label>
          </div>
        </div>
        <% if flash[:errors] %>
          <div class="signup_forms_error group">
            <%= render "layouts/errors" %>
          </div>
        <% end %>
        <div class="signup_forms_button group">
          <input class="sign-up-button" type="submit" value="Sign up">
        </div>
      </form>

      <div class="tumblr_login_link">
          <%= link_to "Log in to your dashboard", new_session_url %>
      </div>
    </div>


  </div>
</body>