config/routes.rb
Runblr::Application.routes.draw do
  resources :users, only: [:create, :new, :destroy, :show, :update, :edit] do
    get 'dashboard'
    resources :follows, only: [:create, :destroy]
  end

  resource :session, :only => [:create, :destroy, :new]

  resource :password_reset

  resources :posts do
    member do
      post "like"
      post "unlike"
    end
    resources :comments, only: [:create, :new, :show, :destroy, :edit] do
      member do
        post "like"
        post "unlike"
      end
    end
  end

  root to: 'sessions#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :post_type, :title, :body, :workout_type, :workout_date, :workout_time, :miles, :hours, :minutes, :seconds, :url, :user_id, :photo

  validates :title, presence: true
  validates :user, presence: true
  validates :photo, presence: { :message => "must be attached" }, if: "post_type == 'photo'"
  validates :body, presence: true, if: "post_type == 'quote'"
  validates :url, presence: true, if: "post_type == 'video' || post_type == 'link'"

  belongs_to :user, inverse_of: :posts
  has_many :user_post_likes, inverse_of: :post
  has_many :comments, inverse_of: :post

  has_attached_file :photo, :styles => {
    :big => "600x600>",
    :small => "420x400#"
  }

  def likes
    self.user_post_likes.sum(:value)
  end

  def comments_by_parent
    comments_by_parent = Hash.new { |hash, key| hash[key] = [] }

    comments.each do |comment|
      comments_by_parent[comment.parent_comment_id] << comment
    end

    comments_by_parent
  end
  
  def self.youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    %Q{<iframe title="YouTube video player" width="420" height="256" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :like, :unlike]
  before_filter :post_exists?, only: [:edit, :show, :update, :like, :unlike]
  before_filter :user_owns_post?, only: [:edit, :update]

  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      redirect_to :back
    #   respond_to do |format|
    #     format.html { render partial: "new_post_template", post: @post}
    #   end
    # end
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to :back
      # head :ok
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find_by_id(params[:post][:id])
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def update
    if @post.update_attributes(params[:post])
      redirect_to :back
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.delete
    
    head :ok
  end

  def like
    @post = Post.find_by_id(params[:id])
    like_total(1)

    respond_to do |format|
      format.html { render partial: "likes_information", post: @post}
    end
  end

  def unlike
    @post = Post.find_by_id(params[:id])

    like_total(0)

    respond_to do |format|
      format.html { render partial: "likes_information", post: @post}
    end
  end



  private
    def post_exists?
      @post = Post.includes(:user_post_likes).find_by_id(params[:id])
      redirect_to :back unless @post
    end

    def like_total(direction)
      @user_post_like = UserPostLike.find_by_post_id_and_user_id(@post.id, current_user.id)

      if @user_post_like
        @user_post_like.update_attributes(value: direction)
      else
        @post.user_post_likes.create(user_id: current_user.id, value: direction)
      end

      # redirect_to :back
    end

    def user_owns_post?
      redirect_to :back unless @post.user == current_user
    end
    

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_likes_information.html.erb
  <div><%= @post.likes %> <%=  @post.likes == 1 ? "like" : "likes" %> </div>
  <ul>
      <% @post.user_post_likes.each do |user_post_like| %>
        <% if user_post_like.value == 1 %>
            <% user = User.find_by_id(user_post_like.user_id) %>
              <div class="username-link-container">
                <li><%= link_to user.username, user_url(user), :class => "username-link" %> likes this </li>
                <% next if current_user == user %>
                <!-- <% if current_user.followed_users.include?(user) %>
                  <td><%= button_to "Unfollow", user_follow_url(user.id, current_user.id), method: :delete %></td>
                <% else %>
                  <td><%= button_to "Follow", user_follows_url(user.id) %></td>
                <% end %> -->
                <li>
                    <%= render "users/follow_button", follower: user %>
                </li>
              </div>
              <br>
          </tr>
        <% end %>
      <% end %>
    </table>
  </ul>

app/views/posts/_likes_template.html.erb
<!-- <% unless current_user.likes_post?(post) %>
  <li><%= link_to "like",  like_post_url(post), method: :post%></li>
<% else %>
  <li><%= link_to "unlike",  unlike_post_url(post), method: :post%></li>
<% end %> -->
<li>

<div class="like-button-container">
  <span class="like-buttons<%= " can-like" if !current_user.likes_post?(post) %> ">

  <form action="<%= unlike_post_url(post) %> " method="post"
         class="unlike posts-liking-form" data-id="<%= post.id %>">
    <input type="hidden" name="authenticity_token"
                        value="<%= form_authenticity_token %>">

    <input type="submit" name="commit" value="Unlike" class="like-button-submit">
  </form>

  <form action="<%= like_post_url(post) %>" method="post"
         class="like posts-liking-form" data-id="<%= post.id %>">
    <input type="hidden" name="authenticity_token"
                        value="<%= form_authenticity_token %>">

    <input type="submit" name="commit" value="Like" class="like-button-submit">
  </form>

  </span>
</div>

</li>

<li class="like-info-container data-post-likes-<%= post.id %>">
  <div><%= post.likes %> <%=  post.likes == 1 ? "like" : "likes" %> </div>
  <ul>
      <% post.user_post_likes.each do |user_post_like| %>
        <% if user_post_like.value == 1 %>
            <% user = User.find_by_id(user_post_like.user_id) %>
              <div class="username-link-container">
                <li><%= link_to user.username, user_url(user), :class => "username-link"%> likes this</li>
                <% next if current_user == user %>
                <!-- <% if current_user.followed_users.include?(user) %>
                  <td><%= button_to "Unfollow", user_follow_url(user.id, current_user.id), method: :delete %></td>
                <% else %>
                  <td><%= button_to "Follow", user_follows_url(user.id) %></td>
                <% end %> -->
                <li><%= render "users/follow_button", follower: user %></li>
              </div>
              <br>
        <% end %>
      <% end %>
  </ul>
</li>

app/views/posts/_new_post_template.html.erb
<li class="post_container">
  <div class="post">
    <div class="post_avatar">
      <a class="post_avatar_link" href="<%= user_url(@post.user) %>">
        <div class="post_avatar">
          <% if @post.user.has_profile_picture %>
            <img src="<%= @post.user.profile_picture.url(:small) %>">
          <% else %>
            <img src="<%=asset_path "blank_profile.png"%>">
          <% end %>
        </div>
      </a>
    </div>
    <div class="post_wrapper">
      <div class="post_header group">
        
        <div class="username-link-header-container">
          <div class="username-link-container">
          <%= link_to @post.user.username, user_url(@post.user), :class => "username-link" %>
          <% unless current_user == @post.user %>
              <%= render "users/follow_button", follower: @post.user %>
          <% end %>
          </div>
        </div>
        <% if @post.user == current_user %>
        
          <div class="delete-post-container">
          
            <form action="<%= post_url(@post.id) %> " method="post"
                   class="delete-post" data-id="<%= @post.id %>">
              <input type="hidden" name="authenticity_token"
                                  value="<%= form_authenticity_token %>">
              <input type="hidden" name="_method" value="delete">

              <input type="submit" name="commit" value="Delete" class="delete-post-button" data-confirm='Are you sure?'>
            </form>
          
          </div>
          
        <% end %>
        
      </div>
      <div class="post_content">
        <%= render "posts/post_content_template", post: @post %>
      </div>
      <div class="post_footer">
        <%= render "posts/post_footer_template", post: @post%>
      </div>
    </div>
  </div>
</li>

app/views/posts/_new_template.html.erb
<nav>
  New Post
  <ul>
    <li>
      Ru
      <%= render "posts/post_form", post: post, post_type: "run" %>
    </li>
    <li>
      Ph
      <%= render "posts/post_form", post: post, post_type: "photo" %>
    </li>
    <li>
      Li
      <%= render "posts/post_form", post: post, post_type: "link" %>
    </li>
    <li>
      Qu
      <%= render "posts/post_form", post: post, post_type: "quote" %>
    </li>
    <li>
      Vi
      <%= render "posts/post_form", post: post, post_type: "video" %>
    </li>
  <ul>
</nav>

app/views/posts/_post_content_template.html.erb
<ul>
  <div class="post_title">
    <h2><%= link_to post.title, post_url(post) %></h2>
  </div>
  <div class="post_body">
    <ul>
      <% unless post.workout_date.nil? %>
        <li><b>Workout Date:</b> <%= post.workout_date %></li>
      <% end %>
      <% unless post.workout_time.nil? %>
        <li><b>Workout Time:</b> <%= post.workout_time %></li>
      <% end %>
      <% unless post.workout_time.nil? %>
        <li><b>Run Type:</b> <%= post.workout_type %> Run</li>
      <% end %>
      <% unless post.miles.nil? %>
        <li><b>Total Miles:</b> <%= post.miles %> </li>
      <% end %>
      <% unless post.hours.nil? && post.minutes.nil? && post.seconds.nil? %>

        <% if post.hours.nil? %>
          <% post.hours = 0 %>
        <% end %>
        <% if post.minutes.nil? %>
          <% post.minutes = 0 %>
        <% end %>
        <% if post.seconds.nil? %>
          <% post.seconds = 0 %>
        <% end %>
          <li><b>Time:</b> <%= "%02d" % post.hours %>:<%= "%02d" % post.minutes %>:<%= "%02d" % post.seconds %></li>
      <% end %><br>
      
      <li><%= post.body %></li>

      <% if post.post_type == "photo" %>
        <li><img src="<%= post.photo.url(:small) %>"></li>
      <% end %>
      
      <% if post.post_type == "video" %>
        <li><%= raw(Post.youtube_embed(post.url)) %></li>
      <% end %>
      
      <% if post.post_type == "link"  %>
        <% object = LinkThumbnailer.generate(post.url) %>
        <div class="link-info-container group">
          <div class="link-title">
            <li><a href="<%=  object.url %>"><%= object.title %></a></li>
            <br>
            <li><%= object.description %></li>
          </div>
          <div class="link-picture">
            <li><a href="<%=  object.url %>"><img src="<%= object.images.first %>"></a></li>
          </div>
        </div>
      <% end %>
      
    </ul>
  </div>
</ul>

app/views/posts/_post_footer_template.html.erb
<ul>
   <ul>
     <%= render "posts/likes_template", post: post %>
   </ul>
   <ul>

       <li>
         <div class="post-comment-title"> Post Comment
           <%= render "comments/new_template", post: post %>
         </div>
       </li>

     <div>
       <ul>
         <%= render "comments/comments_template", post: post %>
       </ul>
     </div>
   </ul>
</ul>

app/views/posts/_post_form.html.erb
<form action="<%= posts_url %>" method="POST"  enctype="multipart/form-data" class="post-form">


  <input type="hidden" name="post[post_type]" value="<%= post_type %>">

  <h1> New <%= post_type %> </h1>
  <br>

  Title: <input class="post_<%= post_type %>_title" name="post[title]" value="<%= post.title %>" style="width: 366px"><br><br>

  <% if post_type == "run" %>
    Date: <input class="post_date" type="date" name="post[workout_date]" value="<%post.workout_date%>" style="text-align:center"><br><br>
    Time: <input class="post_time" type="time" name="post[workout_time]" value="<%post.workout_time%>" style="text-align:center"><br><br>
  <% end %>

  <% if post_type == "run" %>

    Workout Type:
      <select class="post_workout_type" name="post[workout_type]">
        <option value="Regular" "selected">Regular</option><br>
        <option value="Speed">Speed</option><br>
        <option value="Long">Long</option><br>
        <option value="Tempo">Tempo</option><br>
        <option value="Easy">Easy</option><br>
        <option value="Race">Race</option><br>
      </select> <br><br>

    Miles: <input class="post_miles" name="post[miles]" value="<%= post.miles %>" maxlength="4" size="4"><br><br>

    Duration: <input class="post_hours" name="post[hours]" value="<%= post.hours %>" maxlength="2" size="2"
                style="text-align:center" placeholder="00">
                    : <input class="post_minutes" name="post[minutes]" value="<%= post.minutes %>" maxlength="2"size="2"
                    style="text-align:center" placeholder="00">
                    : <input class="post_seconds" name="post[seconds]" value="<%= post.seconds %>" maxlength="2" size="2"
                    style="text-align:center" placeholder="00"><br><br>


  <% end %>

  <% if post_type == "run" || post_type == "quote" %>

    <textarea class="post_<%= post_type %>_description" style="width:398px; height:50px" name="post[body]" value="<%= post.body %>"></textarea><br>

  <% end %>

  <% if post_type == "link" || post_type == "video" %>

    URL: <input class="post_<%= post_type %>_url" name="post[url]" value="<%= post.url %>" style="width: 362px"><br>

  <% end %>

  <% if post_type == "photo" %>

    <input type="file" name="post[photo]" multiple onchange="handle_files(this.files)">
    <br>

  <% end %>

  <br>
  <div class="submit-post">
    <input type="Submit" value="Submit">
  </div>
  
  <% unless post_type == "photo" %>
    <div class="fill-form fill-form-<%= post_type %>">
      <input type="Submit" value="Click here to fill with sample data.">
    </div>
    <% end %>
  
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  

</form>

app/views/posts/_show_template.html.erb
<% if show_all %>
  <% feed_posts = user.get_user_posts_feed %>
<% else %>
  <% feed_posts = user.posts %>
<% end %>

<div class="post-errors">
  <% if flash[:errors] %>
   <p> Oops. Something went wrong. </p>
    <% flash[:errors].each do |error| %>
      <p><%= error %> </p>
    <% end %>
  <% end %>
</div>

<div class="post-count">
  <h2> Posts </h2>
</div>

<ul class="posts-container">

  <div class="posts-list">
   <% feed_posts.reverse.each do |post| %>

     <li class="post_container">
       <div class="post">
         <div class="post_avatar">
           <a class="post_avatar_link" href="<%= user_url(post.user) %>">
             <div class="post_avatar">
               <% if post.user.has_profile_picture %>
                 <img src="<%= post.user.profile_picture.url(:small) %>">
               <% else %>
                 <img src="<%=asset_path "blank_profile.png"%>">
               <% end %>
             </div>
           </a>
         </div>
         <div class="post_wrapper">
           <div class="post_header group">
             <div class="username-link-header-container">
               <div class="username-link-container">
                 <%= link_to post.user.username, user_url(post.user), :class => "username-link" %>
                 <% unless current_user == post.user %>
                     <%= render "users/follow_button", follower: post.user %>
                 <% end %>
               </div>
             </div>
             <% if post.user == current_user %>
               <div class="delete-post-container">
               
                 <form action="<%= post_url(post.id) %> " method="post"
                        class="delete-post" data-id="<%= post.id %>">
                   <input type="hidden" name="authenticity_token"
                                       value="<%= form_authenticity_token %>">
                   <input type="hidden" name="_method" value="delete">

                   <input type="submit" name="commit" value="Delete" class="delete-post-button" data-confirm='Are you sure?'>
                 </form>
               
               </div>
             <% end %>
           </div>
           <div class="post_content">
             <%= render "posts/post_content_template", post: post %>
           </div>
           <div class="post_footer">
             <%= render "posts/post_footer_template", post: post%>
           </div>
         </div>
       </div>
     </li>
   <% end %>
 </div>
</ul>

app/views/posts/show.html.erb
<head>
  <title>Runblr </title>
  <%= stylesheet_link_tag    "dashboard" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<% post = @post %>



<div class="post_wrapper_individual">
  
  <div class="post_header_individual group">
    <h2 class="header-logo">
      <% if current_user.nil? %>
        <%= link_to "Create an Account", new_user_url %>
      <% else %>
        <%= link_to "Dashboard", user_dashboard_url(current_user) %>
      <% end %>
    </h2>
  </div>
  
  <div class="post_header group">
    <div class="username-link-header-container">
      <div class="username-link-container">
        <%= link_to post.user.username, user_url(post.user), :class => "username-link" %>
        <% unless current_user == post.user %>
            <%= render "users/follow_button", follower: post.user %>
        <% end %>
      </div>
    </div>
    <% if post.user == current_user %>
      <div class="delete-post-container">
      
        <form action="<%= post_url(post.id) %> " method="post"
               class="delete-post" data-id="<%= post.id %>">
          <input type="hidden" name="authenticity_token"
                              value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">

          <input type="submit" name="commit" value="Delete" class="delete-post-button" data-confirm='Are you sure?'>
        </form>
      
      </div>
    <% end %>
  </div>
  <div class="post_content">
    <%= render "posts/post_content_template", post: post %>
  </div>
  <div class="post_footer">
    <%= render "posts/post_footer_template", post: post%>
  </div>
</div>
        
</body>
        
<script>
$(document).ready(function(event){


  // FOLLOW BUTTONS

  function toggleFollowButtons ($dataid) {
      $(".user_follow_"+$dataid).toggleClass("can-follow");
  }

  $(".post_wrapper_individual").on("submit", ".follow-form", function (event) {
    event.preventDefault();
    var $currentTarget = $(event.currentTarget);

    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: $currentTarget.serializeJSON(),
      success: function (right_column) {
        toggleFollowButtons($form.attr("data-id"));
      }
    });
  });

  // NEW POST


  $("form.post-form").on("submit", function (event) {
    event.preventDefault();

    var $currentTarget = $(event.currentTarget);
    var data = $currentTarget.serializeJSON();
    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: data,
      success: function (post) {
        $("div.posts-list").prepend(post);
        $("."+data.post.post_type+"-post").toggleClass("hide");
        $form.each(function() {
          this.reset();
        });
      }
    });
  });

  // DELETE POST

  $(".posts-container").on("submit", ".delete-post", function (event) {
    event.preventDefault();

    var $currentTarget = $(event.currentTarget);
    var $post = $(this).parents(".post_container");
    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "DELETE",
      success: function () {
        $post.remove();
      }
    });
  });

  // POST LIKES

  function togglePostLikeButtons ($button) {
    $button
      .parents(".like-buttons")
      .toggleClass("can-like");
  }

  $(".post_wrapper_individual").on("submit", ".posts-liking-form", function (event) {
    event.preventDefault();
    var $currentTarget = $(event.currentTarget);

    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: $currentTarget.serializeJSON(),
      success: function (like_info) {
        togglePostLikeButtons($currentTarget);
        $(".data-post-likes-"+$form.attr("data-id")).html(like_info)
      }
    });
  });

  // NEW COMMENT

  $(".post_wrapper_individual").on("submit", ".new-comment-form", function (event) {
    event.preventDefault();

    var $currentTarget = $(event.currentTarget);
    var data = $currentTarget.serializeJSON();
    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: data,
      success: function (comments) {
        $(".data-post-comments-"+$form.attr("post-id")).html(comments)
        $form.each(function() {
          this.reset();
        });
      }
    });
  });

  // DELETE COMMENT

  $(".post_wrapper_individual").on("submit", ".delete-comment", function (event) {
    event.preventDefault();

    var $currentTarget = $(event.currentTarget);
    var $comment = $(this).parents(".sub-comment:first");
    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "DELETE",
      success: function () {
        $comment.remove();
      }
    });
  });

  // COMMENT LIKES

  function toggleCommentLikeButtons ($button) {
    $button
      .parents(".comment-like-buttons")
      .toggleClass("comment-can-like");
  }

  $(".post_wrapper_individual").on("submit", ".comments-liking-form", function (event) {
    event.preventDefault();
    var $currentTarget = $(event.currentTarget);

    var $form = $(this);

    $.ajax({
      url: $form.attr("action"),
      type: "POST",
      data: $currentTarget.serializeJSON(),
      success: function (like_info) {
        toggleCommentLikeButtons($currentTarget);
        $(".data-comment-likes-"+$form.attr("data-id")).html(like_info)
      }
    });
  });



  // HOVER FOLLOW BUTTONS

  $(document).on('mouseover', ".username-link-container", function() {
    $(this).find(".follow-button-container").show();
  }).on('mouseout',  ".username-link-container", function() {
    $(this).find(".follow-button-container").hide();
  });

  // POP UP COMMENT BOXES

  $(document).on("click", ".post-comment-title", function() {
    $(this).find(".new-comment-container").toggleClass("hide");
  }).on("click", ".post-comment-title", function() {
    $(this).find(".comment-text-box").click(function(e) {
    return false;
  });
  });
});


</script>